/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ubivelox_security_EncryptionKeyStore */

#ifndef _Included_com_ubivelox_security_EncryptionKeyStore
#define _Included_com_ubivelox_security_EncryptionKeyStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ubivelox_security_EncryptionKeyStore
 * Method:    checkRooting
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ubivelox_security_EncryptionKeyStore_checkRooting
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ubivelox_security_EncryptionKeyStore
 * Method:    getBleInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ubivelox_security_EncryptionKeyStore_getBleInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_ubivelox_security_EncryptionKeyStore
 * Method:    getSecretKeyEx
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ubivelox_security_EncryptionKeyStore_getSecretKeyEx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
